import Banner from "../components/Banner";
import Nav from "../components/Nav";
import Footer from "../components/Footer";
import Head from "../components/Head";
import { useTrans } from "../lib/trans";

import TermsOfUseEs from "../contents/legal_es.md";
import TermsOfUseEn from "../contents/legal_en.md";

const LegalEn = () => (
  <>
    <h1>TERMS OF USE</h1>
    <p>
      Welcome to Activazon, a service that analyzes and detects crime in
      neighborhoods to help residents and travelers stay informed and safe.
      These Terms of Use ("Terms") govern your access to and use of the
      Activazon website, located at https://activazon.com, and any content,
      services, or features made available on or through the website (the
      "Service"). By accessing or using the Service, you agree to be bound by
      these Terms. If you do not agree to these Terms, you may not access or use
      the Service.
    </p>
    <h2>INTELLECTUAL PROPERTY</h2>
    <p>
      The Service uses publicly available information to generate summaries, and
      we do not claim ownership of this information. The summaries generated by
      the Service are protected by copyright laws. You may not reproduce,
      distribute, or create derivative works from these summaries without our
      express written consent.
    </p>
    <p>
      The Activazon website and the content, services, and features made
      available on or through the website, including but not limited to text,
      graphics, images, and software, are the property of Activazon or its
      licensors and are protected by copyright and trademark laws. You may not
      use any content, services, or features made available on or through the
      website for any commercial purpose without the express written consent of
      Activazon.
    </p>
    <h2>MODIFICATIONS TO THE SERVICE</h2>
    <p>
      Activazon reserves the right to modify or discontinue the Service, or any
      content, services, or features made available on or through the Service,
      at any time and without notice. We will not be liable to you or any third
      party for any modification, suspension, or discontinuation of the Service.
    </p>
    <h2>DISCLAIMER OF WARRANTIES</h2>
    <p>
      The Service is provided on an "as is" and "as available" basis. We make no
      representations or warranties of any kind, express or implied, as to the
      operation of the Service or the information, content, materials, or
      products included on the Service. We do not warrant that the Service, or
      any content, services, or features made available on or through the
      Service, will be uninterrupted or error-free.
    </p>
    <h2>LIMITATION OF LIABILITY</h2>
    <p>
      We will not be liable for any damages of any kind arising from the use of
      the Service, including but not limited to direct, indirect, incidental,
      punitive, and consequential damages.
    </p>
    <h2>INDEMNIFICATION</h2>
    <p>
      You agree to indemnify and hold Activazon, and its affiliates, officers,
      agents, and employees, harmless from any claim or demand, including
      reasonable attorneys' fees, made by any third party due to or arising out
      of your use of the Service, your violation of these Terms, or your
      violation of any rights of another.
    </p>
    <h2>GOVERNING LAW</h2>
    <p>
      These Terms and your use of the Service shall be governed by and construed
      in accordance with the laws of the United States, without giving effect to
      any principles of conflicts of law. Any legal action or proceeding arising
      out of or related to these Terms or the Service shall be brought
      exclusively in the federal or state courts located in the United States.
    </p>
    <h2>SEVERABILITY</h2>
    <p>
      If any provision of these Terms is found to be invalid or unenforceable,
      that provision shall be enforced to the maximum extent possible, and the
      remaining provisions shall remain in full force and effect.
    </p>
    <h2>ENTIRE AGREEMENT</h2>
    <p>
      These Terms constitute the entire agreement between you and Activazon with
      respect to the Service, and supersede all prior or contemporaneous
      communications and proposals, whether oral or written.
    </p>
    <h2>CONTACT US</h2>
    <p>
      If you have any questions about these Terms, please contact us at
      info@activazon.com.
    </p>
  </>
);

const LegalEs = () => (
  <>
    <h1>TÉRMINOS DE USO</h1>
    <p>
      Bienvenido a Activazon, un servicio que analiza y detecta el delito en los
      vecindarios para ayudar a los residentes y viajeros a estar informados y
      seguros. Estos Términos de uso ("Términos") rigen el acceso y uso del
      sitio web de Activazon, ubicado en https://activazon.com, y cualquier
      contenido, servicios o características disponibles en o a través del sitio
      web (el "Servicio"). Al acceder o utilizar el Servicio, usted acepta estar
      sujeto a estos Términos. Si no está de acuerdo con estos Términos, no
      puede acceder ni utilizar el Servicio.
    </p>
    <h2>PROPIEDAD INTELECTUAL</h2>
    <p>
      El Servicio utiliza información disponible públicamente para generar
      resúmenes y no reclama la propiedad de esta información. Los resúmenes
      generados por el Servicio están protegidos por las leyes de derechos de
      autor. No puede reproducir, distribuir ni crear trabajos derivados de
      estos resúmenes sin nuestro consentimiento por escrito.
    </p>
    <p>
      El sitio web de Activazon y el contenido, servicios y características
      disponibles en o a través del sitio web, incluyendo pero no limitado a
      texto, gráficos, imágenes y software, son propiedad de Activazon o de sus
      licenciatarios y están protegidos por leyes de derechos de autor y marcas
      comerciales. No puede utilizar ningún contenido, servicios o
      características disponibles en o a través del sitio web con fines
      comerciales sin el consentimiento por escrito de Activazon.
    </p>
    <h2>MODIFICACIONES AL SERVICIO</h2>
    <p>
      Activazon se reserva el derecho a modificar o descontinuar el Servicio, o
      cualquier contenido, servicios o características disponibles a través del
      Servicio, en cualquier momento y sin previo aviso. No nos hacemos
      responsables ante ti ni ante terceros por cualquier modificación,
      suspensión o descontinuación del Servicio.
    </p>
    <h2>RENUNCIA DE GARANTÍAS</h2>
    <p>
      El Servicio se proporciona "tal cual" y "según esté disponible". No
      hacemos representaciones ni garantías de ningún tipo, ya sean expresas o
      implícitas, en cuanto al funcionamiento del Servicio o la información,
      contenido, materiales o productos incluidos en el Servicio. No
      garantizamos que el Servicio, ni cualquier contenido, servicios o
      características disponibles a través del Servicio, serán ininterrumpidos o
      libres de errores.
    </p>
    <h2>LIMITACIÓN DE RESPONSABILIDAD</h2>
    <p>
      No nos hacemos responsables por daños de ningún tipo que surjan del uso
      del Servicio, incluyendo pero no limitados a daños directos, indirectos,
      incidentales, punitivos y consecuenciales.
    </p>
    <h2>INDEMNIZACIÓN</h2>
    <p>
      Usted acepta indemnizar y eximir de responsabilidad a Activazon y a sus
      afiliados, funcionarios, agentes y empleados de cualquier reclamo o
      demanda, incluyendo honorarios razonables de abogados, presentado por
      cualquier tercero debido o derivado de su uso del Servicio, su violación
      de estos Términos o su violación de los derechos de otra persona.
    </p>
    <h2>LEY APLICABLE</h2>
    <p>
      Estos Términos y su uso del Servicio se regirán e interpretarán de acuerdo
      con las leyes de los Estados Unidos, sin tener en cuenta ningún principio
      de conflictos de leyes. Cualquier acción legal o procedimiento surgido de
      o relacionado con estos Términos o el Servicio se llevará a cabo
      exclusivamente en los tribunales federales o estatales de los Estados
      Unidos.
    </p>
    <h2>SEVERABILIDAD</h2>
    <p>
      Si se determina que cualquier disposición de estos Términos es inválida o
      inaplicable, esa disposición se aplicará en la máxima medida posible y las
      demás disposiciones permanecerán plenamente en vigor.
    </p>
    <h2>SEVERABILIDAD</h2>
    <p>
      Si se determina que alguna disposición de estos Términos es inválida o
      inaplicable, esa disposición se aplicará en la máxima medida posible y las
      demás disposiciones permanecerán plenamente en vigor y efecto.
    </p>
    <h2>ACUERDO COMPLETO</h2>
    <p>
      Estos Términos constituyen el acuerdo completo entre usted y Activazon en
      relación con el Servicio y sustituyen a todas las comunicaciones y
      propuestas anteriores o contemporáneas, ya sean orales o escritas.
    </p>
    <h2>CONTÁCTENOS</h2>
    <p>
      Si tiene alguna pregunta sobre estos Términos, póngase en contacto con
      nosotros en info@activazon.com.
    </p>
  </>
);

export default function Home({}) {
  const { i, locale } = useTrans();
  const content = locale === "es" ? <LegalEs /> : <LegalEn />;

  return (
    <>
      <Head title={i("Terms of Use")} />
      <body>
        <div className="page">
          <Nav />
          <main>
            <Banner title={i("Terms of Use")} showSearch={false} />

            <div className="container pt-3">
              <ReactMarkdown>{content}</ReactMarkdown>
            </div>
            <Footer />
          </main>
        </div>
      </body>
    </>
  );
}
