export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div>
          <nav>
            <p>Hello</p>
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
